### ISSUE TITLE
Visualizar horários por dia (plantonista)

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_API#44]
Nessa issue deve ser feito:
- [x] Disponibilizar listas de horários de plantão em um dia especifico
 - Inicio
 - Fim
 - Setor
 - Especialidade
- [ ] Disponibilizar horas de plantão na semana
 - Somatório de horas trabalhas na semana

**Comment by eliseuegewarth** [comment]
Fixed at PR #61
